version: '3'
services: 
  db: 
    image: mysql:5.7.31
    container_name: db
    environment: 
      MYSQL_ROOT_PASSWORD: minh
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: minh
      MYSQL_PASSWORD: minh 
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/
    networks:
      - backend
  redishost:
    image: redis
    container_name: redishost
    networks:
      - backend
    volumes:
      - ./redis/redis.conf /etc/redis
  webapp:
    build: './nodejs'
    networks:
      - frontend
      - backend
  balancer: 
    build: './load-balancer'
    container_name: balancer
    networks:
      - frontend
    privileged: true
    ports:
      - "800:8000"
networks:
  frontend:
  backend:
